language: objective-c
osx_image: xcode7.1

notifications:
  email: false

before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - curl -OlL "https://github.com/Carthage/Carthage/releases/download/0.11/Carthage.pkg"
  - sudo installer -pkg "Carthage.pkg" -target /
  - rm "Carthage.pkg"

before_script:
  - cd SmartDeviceLink-iOS
  - carthage bootstrap --platform ios
  - cd ../

script:
  - xctool -project SmartDeviceLink-iOS/SmartDeviceLink-iOS.xcodeproj -scheme SmartDeviceLink -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO RUN_CLANG_STATIC_ANALYZER=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES test

after_script:
  - bash <(curl -s https://codecov.io/bash)